# Generated by Django 4.2.25 on 2025-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_onlinemba_assigned_to_realestatelead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatelead',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Land'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='sub_industry',
            field=models.CharField(blank=True, choices=[('Buyers Leads', 'Buyers Leads'), ('Tenant Leads', 'Tenant Leads')], max_length=20, null=True),
        ),
    ]
