# Generated by Django 4.2.25 on 2025-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_realestatelead_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestatelead',
            old_name='interested_to_visit',
            new_name='visit_day',
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
