# Generated by Django 4.2.25 on 2025-10-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_interested_to_visit_realestatelead_visit_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemba',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyabroad',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
