# Generated by Django 4.2.25 on 2025-10-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0005_onlinemba_remark_studyabroad_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='How much experience')),
                ('broker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Initially using broker')),
                ('initial_investment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Initial investment for trading')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
