# Generated by Django 4.2.25 on 2025-11-12 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('leads', '0006_forextrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forextrade',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadassignmentlog',
            name='status_at_assignment',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='onlinemba',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='realestatelead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyabroad',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_object_id', models.PositiveIntegerField()),
                ('old_status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('lead_replacement', 'Lead Replacement'), ('converted', 'Converted'), ('not_converted', 'Not Converted'), ('trashed', 'Trashed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Lead Status History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRemarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_object_id', models.PositiveIntegerField()),
                ('remark_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_remarks', to=settings.AUTH_USER_MODEL)),
                ('lead_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Lead Remark History',
                'ordering': ['-created_at'],
            },
        ),
    ]
