# Generated by Django 4.2.25 on 2025-11-20 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribers', '0004_ticket_replacement_leads'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('leads', '0007_alter_forextrade_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadReplacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_lead_object_id', models.PositiveIntegerField()),
                ('new_lead_object_id', models.PositiveIntegerField()),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('new_lead_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_lead_replacements', to='contenttypes.contenttype')),
                ('old_lead_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_lead_replacements', to='contenttypes.contenttype')),
                ('replaced_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_replacements_done', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_replacements_received', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribers.ticket')),
            ],
            options={
                'verbose_name_plural': 'Lead Replacement History',
                'ordering': ['-replaced_at'],
            },
        ),
    ]
