# Generated by Django 4.2.25 on 2025-11-21 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_leadreplacementhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='forextrade',
            name='replaced_for_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_replaced_leads', to=settings.AUTH_USER_MODEL, verbose_name='Users this lead was replaced for'),
        ),
        migrations.AddField(
            model_name='onlinemba',
            name='replaced_for_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_replaced_leads', to=settings.AUTH_USER_MODEL, verbose_name='Users this lead was replaced for'),
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='replaced_for_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_replaced_leads', to=settings.AUTH_USER_MODEL, verbose_name='Users this lead was replaced for'),
        ),
        migrations.AddField(
            model_name='studyabroad',
            name='replaced_for_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_replaced_leads', to=settings.AUTH_USER_MODEL, verbose_name='Users this lead was replaced for'),
        ),
    ]
