# Generated by Django 4.2.25 on 2025-11-21 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0009_forextrade_replaced_for_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forextrade',
            name='replaced_for_users',
        ),
        migrations.RemoveField(
            model_name='onlinemba',
            name='replaced_for_users',
        ),
        migrations.RemoveField(
            model_name='realestatelead',
            name='replaced_for_users',
        ),
        migrations.RemoveField(
            model_name='studyabroad',
            name='replaced_for_users',
        ),
        migrations.AddField(
            model_name='forextrade',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forextrade',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forextrade',
            name='replaced_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_replaced_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinemba',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinemba',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinemba',
            name='replaced_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_replaced_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='replaced_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_replaced_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyabroad',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyabroad',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyabroad',
            name='replaced_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_replaced_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
