# Generated by Django 4.2.25 on 2025-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_user_credit_limit_user_credits_used_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_limit',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
