# Generated by Django 4.2.25 on 2025-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_rename_name_payment_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leads_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='real_estate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='working_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='Free', max_length=20),
        ),
    ]
