# Generated by Django 4.2.25 on 2025-10-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_contactlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], default='Free', max_length=20),
        ),
    ]
