# Generated by Django 4.2.25 on 2025-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Buyers Leads', 'Buyers Leads'), ('Tenant Leads', 'Tenant Leads'), ('Study Abroad', 'Study Abroad'), ('Online MBA', 'Online MBA'), ('Certification', 'Certification'), ('Phd/doctorate', 'Phd/doctorate'), ('Forex Market', 'Forex Market')], max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=20)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
