# Generated by Django 4.2.25 on 2025-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_admin', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default='✅ Feature 1\n✅ Feature 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='heading',
            field=models.TextField(default='✅ Feature 1\n✅ Feature 2'),
            preserve_default=False,
        ),
    ]
