# Generated by Django 4.2.25 on 2025-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_admin', '0003_product_features_product_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
