# Generated by Django 4.2.25 on 2025-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_admin', '0004_alter_product_features_alter_product_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Australia', 'Australia'), ('UK', 'UK'), ('Poland', 'Poland'), ('Malaysia', 'Malaysia'), ('Dubai', 'Dubai'), ('Oman', 'Oman'), ('Qatar', 'Qatar'), ('Kuwait', 'Kuwait'), ('Jordan', 'Jordan'), ('Bahrain', 'Bahrain'), ('India', 'India')], default='India', max_length=50),
        ),
    ]
