"""
Django settings for optimizedleads project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

<<<<<<< HEAD
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
=======

import os
from pathlib import Path
from dotenv import load_dotenv

# BASE_DIR already defined? agar nahi to define karo
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Now get variables
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
GOOGLE_PROJECT_ID = os.getenv("GOOGLE_PROJECT_ID")




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


>>>>>>> f8edcb12e3ff2bfa7181978e0c21436a4357e17d

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o^9*r(fcxn)6%hg(-*li(x*&tab1!y27sj+2q=dbugsmim2vk('

# SECURITY WARNING: don't run with debug turned on in production!
<<<<<<< HEAD
DEBUG = False
=======
DEBUG = True
>>>>>>> f8edcb12e3ff2bfa7181978e0c21436a4357e17d

# For local development - allow HTTP
if DEBUG:
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
    os.environ['OAUTHLIB_RELAX_TOKEN_SCOPE'] = '1'

<<<<<<< HEAD
ALLOWED_HOSTS = ['31.97.60.181','optimizedleads.in']
#ALLOWED_HOSTS = ['*']
=======
# ALLOWED_HOSTS = ['31.97.60.181','optimizedleads.in']
ALLOWED_HOSTS = ['*']
>>>>>>> f8edcb12e3ff2bfa7181978e0c21436a4357e17d


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom Apps
    'leads',
    'central_admin',
    'sub_admin',
    'subscribers',
    'landing',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
    'optimizedleads.middlewares.RoleBasedAccessMiddleware',
]

ROOT_URLCONF = 'optimizedleads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'optimizedleads.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ra_db',
        'USER': 'postgres',
        'PASSWORD': 'pass123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'templates')]

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'landing.User'


# import os

RAZORPAY_KEY_ID = 'rzp_live_RWE3SJjrKyS9pf'
RAZORPAY_KEY_SECRET = 'C0dPheXZM3v2bS7rXPRR32u1'

# -------------------------------------------------

# tracking ke liye 
<<<<<<< HEAD
#BASE_URL = "https://14d3a1fbf26d.ngrok-free.app"  # 👈 local testing
=======
BASE_URL = "https://14d3a1fbf26d.ngrok-free.app"  # 👈 local testing
>>>>>>> f8edcb12e3ff2bfa7181978e0c21436a4357e17d
# Hosting ke baad change kar dena:
# BASE_URL = "https://yourdomain.com"



<<<<<<< HEAD
#CSRF_TRUSTED_ORIGINS = [
#    "https://14d3a1fbf26d.ngrok-free.app",
#    "http://127.0.0.1:8000",
#    "http://localhost:8000",
#]
=======
CSRF_TRUSTED_ORIGINS = [
    "https://14d3a1fbf26d.ngrok-free.app",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]
>>>>>>> f8edcb12e3ff2bfa7181978e0c21436a4357e17d
# ---------------------------------------------------------------------------------------