# Generated by Django 4.2.25 on 2025-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('central_admin', 'Central Admin'), ('sub_admin', 'Sub Admin'), ('subscriber', 'Subscriber')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
