# Generated by Django 4.2.25 on 2025-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_googlecalendarauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='replacement_leads',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
